# Generated by Django 6.1.1 on 2026-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
